using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Pathfinding;

public class EnemyAI : MonoBehaviour
{

    public Transform target;
    public float speed = 800f;
    public float nextWayPointDistance = 3f;

    public Transform enemyGFX;

    Path path;
    int currentWaypoint = 0;
    bool reachedEndOfPath = false;

    BoxCollider2D bc;

    Seeker seeker;
    Rigidbody2D rb;

    // Start is called before the first frame update
    void Start()
    {
        seeker = GetComponent<Seeker>();
        rb = GetComponent<Rigidbody2D>();
        bc = GetComponent<BoxCollider2D>();

        InvokeRepeating("UpdatePath", 0f, .5f);

    }

    void UpdatePath()
    {
        if (seeker.IsDone())
        {
            seeker.StartPath(rb.position, target.position, OnPathComplete);
        }
    }

    void OnPathComplete(Path p)
    {
        if (!p.error)
        {
            path = p;
            currentWaypoint = 0;
        }
    }

    // Update is called once per frame
    void FixedUpdate()
    {

        if (path == null) return;
        if (currentWaypoint >= path.vectorPath.Count)
        {
            reachedEndOfPath = true;
            return;
        }
        else
        {
            reachedEndOfPath = false;
        }

        //Obtenemos la nueva direccion normalizando el resultado.
        Vector2 direction = ((Vector2)path.vectorPath[currentWaypoint] - rb.position).normalized;
        Vector2 force = direction * speed * Time.deltaTime;

        rb.AddForce(force);

        float distance = Vector2.Distance(rb.position, path.vectorPath[currentWaypoint]);

        if (distance < nextWayPointDistance)
        {
            currentWaypoint++;
        }

        //Gira el mago segun su direcciÃ³n
        if (rb.velocity.x >= 0.01f)
        {
            //enemyGFX.localScale = new Vector3(1f, 1f, 1f);
            transform.localScale = new Vector3(3.9687f, 3.9687f, 1f);
        }
        else if (rb.velocity.x <= 0.01f)
        {
            //enemyGFX.localScale = new Vector3(-1f, 1f, 1f);
            transform.localScale = new Vector3(-3.9687f, 3.9687f, 1f);
        }
    }

    // when the GameObjects collider arrange for this GameObject to travel to the left of the screen
    void OnTriggerEnter2D(Collider2D player)
    {
        if (player != null && player.name == "Player")
        {
            GetComponent<EnemyCombat>().Attack(player);
            GetComponentInChildren<AnimationController>().setAttackTrigger();
        }
    }


}
